# -*- coding: utf-8 -*-
"""Artist based Recommender System_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEMwKIltK7NigTxDEQTy9vA-P8lE5RsW
"""



!pip install streamlit

from google.colab import drive
drive.mount('/content/drive')

import streamlit as st
from gensim.models import Word2Vec

# Load the trained Word2Vec model
model_path = '/content/drive/MyDrive/Final Project DATA SCIENCE/final4_word2vec_model.model'
model = Word2Vec.load(model_path)

# Streamlit UI
st.title("Personalized Playlist Recommender")
st.header("Enter a preffered song to get a personalized playlist!")

# User input
user_input = st.text_input("Enter song (artistname:trackname):", "")

if user_input:
    try:
        # Get recommendations
        recommendations = model.wv.most_similar(user_input, topn=10)
        recommended_tracks = [rec[0] for rec in recommendations]

        st.write("### Recommended Playlist:")
        for i, track in enumerate(recommended_tracks, 1):
            st.write(f"{i}. {track}")
    except KeyError:
        st.error("Song not found in the model's vocabulary. Please try another song.")